### ISSUE TITLE
Updating the readme of Digital Clock with pictures and emojis and make it look nicer somehow !!! 

### ISSUE THREAD

**Issue by Sohoxic** [Sohoxic/WEB-DEVELOPMENT#16]

**Comment by SHAGNIK007** [comment]
i want to work on  this issue. please assign me the same

**Comment by Sohoxic** [comment]
Yes, you can work on this issue. You have 24 hours to work on this issue starting from now. Try finishing it by EOD if you want your PR to get reflected in hacktoberfest !!!
