### ISSUE TITLE
Improvise Readme.md for this repository by including the list of contributors. 

### ISSUE THREAD

**Issue by Sohoxic** [Sohoxic/WEB-DEVELOPMENT#8]

**Comment by SHAGNIK007** [comment]
i would like to work on this issue. Pliease assign me the same

**Comment by Sohoxic** [comment]
Sure @SHAGNIK007 , are you a hacktoberfest participant?

**Comment by SHAGNIK007** [comment]
yes

**Comment by Sohoxic** [comment]
Okay, fine you can proceed to work on this issue, you have 24 hours starting from now.
